# Generated by Django 3.1 on 2022-08-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
            ],
        ),
    ]
